#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	colorInfo
	consoleModule
	constInfo
	debugInfo
	dragon_soul_refine_settings
	emotion
	exception
	game
	grid
	ingamewiki
	ingamewikiconfig
	ingamewikiui
	interfaceModule
	introCreate
	introEmpire
	introLoading
	introLogin
	introLogo
	introSelect
	localeInfo
	mouseModule
	musicInfo
	networkModule
	playerSettingModule
	Prototype
	rendertargetinfo
	serverCommandParser
	serverInfo
	serverinfo_default
	stringCommander
	system
	test_affect
	ui
	uiacce
	uiAffectShower
	uiantimultiplefarm
	uiAttachMetin
	uiattr67add
	uiAutoban
	uiautoskillreader
	uibattlepass
	uibiologmanager
	uibossgui
	uiCandidate
	uiCharacter
	uicharacterdetails
	uiChat
	uicheckbox
	uichestdropinfo
	uiCommon
	uiCube
	uiDragonSoul
	uidungeoninfo
	uiEquipmentDialog
	uievent
	uieventcalendar
	uiEx
	uiExchange
	uiGameButton
	uiGameOption
	uigameoptionnew
	uigemshop
	uiGuild
	uiHelp
	uihunting
	uihuntingmapnames
	uihwidmanager
	uiInventory
	uiitemmanager
	uiitemshop
	uimaintenance
	uiMapNameShower
	uiMessenger
	uiMiniMap
	uimovechannel
	uimovechannel_default
	uiOption
	uiParty
	uiPhaseCurtain
	uiPickMoney
	uipickupfilter
	uiPlayerGauge
	uiPointReset
	uipreview
	uiprivateshop
	uiPrivateShopBuilder
	uiprivateshopsearch
	uiQuest
	uirankinfo
	uiRefine
	uiremoteshop
	uirendertargetwindow
	uiRestart
	uireward
	uiSafebox
	uiScriptLocale
	uiselectitem
	uiselectitemex
	uiSelectMusic
	uiShop
	uiskillcolor
	uiskillgroup
	uiskybox
	uispinwheel
	uiswitchbot
	uiSystem
	uiSystemOption
	uiTarget
	uiTaskBar
	uiTip
	uiToolTip
	uiUploadMark
	uivote4buff
	uiwarpshower
	uiWeb
	uiWhisper
	utilfile
	utils
*/
void initrootlibManager();
#endif
